name: artbeat_ads
description: ARTbeat Ads module for in-app ad purchasing and management
version: 0.1.1
publish_to: "none"

environment:
  sdk: "^3.8.0"
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  artbeat_core:
    path: ../artbeat_core
  artbeat_admin:
    path: ../artbeat_admin
  artbeat_artist:
    path: ../artbeat_artist
  artbeat_artwork:
    path: ../artbeat_artwork

  artbeat_settings:
    path: ../artbeat_settings
  provider: ^6.1.5
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  firebase_analytics: ^12.0.0
  firebase_app_check: ^0.4.0
  firebase_messaging: ^16.0.0
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.1.0
  google_maps_flutter: ^2.5.3
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  path_provider: ^2.1.5
  http: ^1.4.0
  geocoding: ^4.0.0
  camera: ^0.11.1
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1

  image_picker: any
  url_launcher: ^6.2.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.7
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
